const path = require('path');
const fs = require('fs');
const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

const PORT = process.env.PORT || 3000;
const FILE = path.join(__dirname, 'dayflow-db.json');
const SECRET = process.env.JWT_SECRET || 'dayflow-development-secret';
const names = ['users', 'attendance', 'leaveRequests', 'payroll', 'performance', 'auditEvents'];
const fallback = { users: [], attendance: [], leaveRequests: [], payroll: [], performance: [], auditEvents: [] };
let db;
try { db = JSON.parse(fs.readFileSync(FILE, 'utf8')); } catch { db = fallback; }
names.forEach(name => { if (!Array.isArray(db[name])) db[name] = []; });
function save() { fs.writeFileSync(FILE, `${JSON.stringify(db, null, 2)}\n`, 'utf8'); }
function next(name) { return db[name].reduce((max, item) => Math.max(max, Number(item.id) || 0), 0) + 1; }
function user(id) { return db.users.find(item => item.id === Number(id)); }
function safe(item) { if (!item) return null; const copy = { ...item }; delete copy.passwordHash; delete copy.password; return copy; }
function managed(req, employee) { return req.user.role === 'hr' || (req.user.role === 'manager' && employee?.managerId === req.user.id); }
function auth(req, res, nextMiddleware) { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.user = jwt.verify(token, SECRET); nextMiddleware(); } catch { res.status(401).json({ error: 'Invalid or expired session' }); } }
function management(req, res, nextMiddleware) { return ['hr', 'manager'].includes(req.user.role) ? nextMiddleware() : res.status(403).json({ error: 'Management access required' }); }
function token(item) { return jwt.sign({ id: item.id, role: item.role }, SECRET, { expiresIn: '8h' }); }
function recordAudit(req, action, entity, entityId, details = '') { db.auditEvents.push({ id: next('auditEvents'), actorId: req.user.id, action, entity, entityId, details, createdAt: new Date().toISOString() }); }

const app = express();
app.use(express.json());
app.use(express.static(__dirname));
app.post('/api/auth/signup', (req, res) => { const { employeeId, name, email, password, department = 'General', jobTitle = 'Employee' } = req.body; if (!employeeId || !name || !email || !password || password.length < 8) return res.status(400).json({ error: 'Employee ID, name, email, and an 8+ character password are required' }); if (db.users.some(item => item.email === email.toLowerCase() || item.employeeId === employeeId)) return res.status(409).json({ error: 'Employee ID or email is already registered' }); const item = { id: next('users'), employeeId, name, email: email.toLowerCase(), passwordHash: bcrypt.hashSync(password, 10), role: 'employee', department, jobTitle, phone: '', address: '', salary: 0, managerId: null }; db.users.push(item); save(); res.status(201).json({ user: safe(item), token: token(item) }); });
app.post('/api/auth/signin', (req, res) => { const item = db.users.find(candidate => candidate.email === req.body.email?.toLowerCase()); if (!item || !bcrypt.compareSync(req.body.password || '', item.passwordHash)) return res.status(401).json({ error: 'Incorrect email or password' }); res.json({ user: safe(item), token: token(item) }); });
app.get('/api/me', (req, res) => auth(req, res, () => res.json(safe(user(req.user.id)))));
app.patch('/api/me', (req, res) => auth(req, res, () => { const item = user(req.user.id); if (!item) return res.status(404).json({ error: 'User not found' }); if (typeof req.body.phone === 'string') item.phone = req.body.phone.trim().slice(0, 40); if (typeof req.body.address === 'string') item.address = req.body.address.trim().slice(0, 160); save(); res.json(safe(item)); }));
app.get('/api/dashboard', (req, res) => auth(req, res, () => res.json({ user: safe(user(req.user.id)), attendance: db.attendance.filter(item => item.userId === req.user.id), leave: db.leaveRequests.filter(item => item.userId === req.user.id), leaveBalance: 14 })));
app.get('/api/notifications', (req, res) => auth(req, res, () => { const leaveItems = db.leaveRequests.filter(item => item.userId === req.user.id && item.status !== 'Pending').map(item => ({ id: `leave-${item.id}`, title: `Leave request ${item.status.toLowerCase()}`, message: `${item.type}: ${item.startDate} - ${item.endDate}`, createdAt: item.createdAt })); const auditItems = db.auditEvents.filter(item => item.actorId === req.user.id).map(item => ({ id: item.id, title: item.action.replaceAll('_', ' '), message: item.details || 'Activity recorded', createdAt: item.createdAt })); res.json([...leaveItems, ...auditItems].slice(-20).reverse()); }));
app.post('/api/assistant', (req, res) => auth(req, res, () => { const q = String(req.body.question || '').toLowerCase(); const leaves = db.leaveRequests.filter(item => item.userId === req.user.id); const pay = db.payroll.find(item => item.userId === req.user.id); const attendance = db.attendance.filter(item => item.userId === req.user.id); const review = db.performance.find(item => item.userId === req.user.id); let answer = 'Ask me about attendance, leave, payroll, performance, profile, or check-in status.'; if (/leave|time off/.test(q)) answer = `You have ${leaves.filter(item => item.status === 'Pending').length} pending leave requests and ${leaves.filter(item => item.status === 'Approved').reduce((sum, item) => sum + item.days, 0)} approved leave days.`; else if (/pay|salary|payroll/.test(q)) answer = pay ? `Your net pay is $${pay.netPay.toLocaleString()} after deductions.` : 'No payroll record is available yet.'; else if (/attendance|hours|check/.test(q)) answer = `You have ${attendance.length} attendance records and ${attendance.filter(item => item.checkIn && item.checkOut).length} completed workdays.`; else if (/performance|goal|progress/.test(q)) answer = review ? `Your goal is ${review.goal}, currently at ${review.progress}% progress.` : 'No performance review has been recorded yet.'; res.json({ answer }); }));
app.get('/api/attendance', (req, res) => auth(req, res, () => res.json(db.attendance.filter(item => item.userId === req.user.id))));
app.post('/api/attendance/check-in', (req, res) => auth(req, res, () => { const date = req.body.workDate || new Date().toISOString().slice(0, 10); if (db.attendance.some(item => item.userId === req.user.id && item.workDate === date)) return res.status(409).json({ error: 'Attendance already exists for this date' }); const item = { id: next('attendance'), userId: req.user.id, workDate: date, checkIn: new Date().toTimeString().slice(0, 5), checkOut: null, status: 'Present' }; db.attendance.push(item); recordAudit(req, 'attendance_checked_in', 'attendance', item.id); save(); res.status(201).json(item); }));
app.patch('/api/attendance/check-out', (req, res) => auth(req, res, () => { const item = db.attendance.find(candidate => candidate.userId === req.user.id && candidate.workDate === (req.body.workDate || new Date().toISOString().slice(0, 10))); if (!item) return res.status(404).json({ error: 'Check-in record not found for this date' }); item.checkOut = new Date().toTimeString().slice(0, 5); recordAudit(req, 'attendance_checked_out', 'attendance', item.id); save(); res.json(item); }));
app.get('/api/leaves', (req, res) => auth(req, res, () => res.json(db.leaveRequests.filter(item => item.userId === req.user.id))));
app.post('/api/leaves', (req, res) => auth(req, res, () => { const { type, startDate, endDate, days, remarks = '' } = req.body; if (!type || !startDate || !endDate || Number(days) < 1 || new Date(endDate) < new Date(startDate)) return res.status(400).json({ error: 'Leave type, valid dates, and duration are required' }); const item = { id: next('leaveRequests'), userId: req.user.id, type, startDate, endDate, days: Number(days), remarks: String(remarks).slice(0, 500), status: 'Pending', managerComment: '', createdAt: new Date().toISOString() }; db.leaveRequests.push(item); save(); res.status(201).json(item); }));
app.get('/api/payroll', (req, res) => auth(req, res, () => { const item = db.payroll.find(candidate => candidate.userId === req.user.id); item ? res.json(item) : res.status(404).json({ error: 'Payroll record not found' }); }));
app.get('/api/performance', (req, res) => auth(req, res, () => res.json(db.performance.filter(item => item.userId === req.user.id))));
app.get('/api/admin/employees', (req, res) => auth(req, res, () => management(req, res, () => res.json(db.users.filter(item => req.user.role === 'hr' || item.managerId === req.user.id).map(safe)))));
app.get('/api/admin/attendance', (req, res) => auth(req, res, () => management(req, res, () => { const result = db.attendance.filter(item => managed(req, user(item.userId))).map(item => ({ ...item, employeeName: user(item.userId)?.name || 'Unknown employee' })); res.json(result); })));
app.get('/api/admin/leaves', (req, res) => auth(req, res, () => management(req, res, () => { const result = db.leaveRequests.filter(item => managed(req, user(item.userId))).map(item => ({ ...item, employeeName: user(item.userId)?.name || 'Unknown employee' })); res.json(result); })));
app.get('/api/admin/performance', (req, res) => auth(req, res, () => management(req, res, () => { const result = db.performance.filter(item => managed(req, user(item.userId))).map(item => ({ ...item, employeeName: user(item.userId)?.name || 'Unknown employee' })); res.json(result); })));
app.patch('/api/admin/leaves/:id', (req, res) => auth(req, res, () => management(req, res, () => { const item = db.leaveRequests.find(candidate => candidate.id === Number(req.params.id)); if (!item || !managed(req, user(item.userId))) return res.status(403).json({ error: 'You cannot manage this leave request' }); if (!['Approved', 'Rejected'].includes(req.body.status)) return res.status(400).json({ error: 'Status must be Approved or Rejected' }); item.status = req.body.status; item.managerComment = req.body.comment || ''; recordAudit(req, `leave_${item.status.toLowerCase()}`, 'leave', item.id, item.managerComment); save(); res.json(item); })));
app.patch('/api/admin/employees/:id/payroll', (req, res) => auth(req, res, () => management(req, res, () => { const employee = user(req.params.id); const grossPay = Number(req.body.grossPay); const deductions = Number(req.body.deductions || 0); if (!employee || !managed(req, employee) || !grossPay || grossPay < deductions) return res.status(400).json({ error: 'Valid salary values are required' }); let item = db.payroll.find(candidate => candidate.userId === employee.id); if (!item) { item = { id: next('payroll'), userId: employee.id }; db.payroll.push(item); } Object.assign(item, { grossPay, deductions, netPay: grossPay - deductions }); employee.salary = grossPay; recordAudit(req, 'payroll_updated', 'payroll', employee.id); save(); res.json(item); })));
app.patch('/api/admin/employees/:id/performance', (req, res) => auth(req, res, () => management(req, res, () => { const employee = user(req.params.id); if (!employee || !managed(req, employee)) return res.status(403).json({ error: 'You cannot manage this employee' }); let item = db.performance.find(candidate => candidate.userId === employee.id); if (!item) { item = { id: next('performance'), userId: employee.id }; db.performance.push(item); } Object.assign(item, { userId: employee.id, managerId: req.user.id, goal: req.body.goal || '', progress: Math.max(0, Math.min(100, Number(req.body.progress || 0))), feedback: req.body.feedback || '', commitmentStatus: req.body.commitmentStatus || 'High', reviewStatus: req.body.reviewStatus || 'On track', updatedAt: new Date().toISOString() }); recordAudit(req, 'performance_updated', 'performance', employee.id); save(); res.json(item); })));
app.use('/api', (req, res) => res.status(404).json({ error: 'API endpoint not found' }));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));

save();
app.listen(PORT, () => console.log(`Dayflow running at http://localhost:${PORT} using local JSON storage`));