const path = require('path');
const fs = require('fs');
const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const initSqlJs = require('sql.js');

const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'dayflow-development-secret';
const DB_FILE = path.join(__dirname, 'dayflow.sqlite');
const LEGACY_FILE = path.join(__dirname, 'dayflow-db.json');

function rows(db, sql, params = []) { const result = db.exec(sql, params); if (!result.length) return []; const columns = result[0].columns; return result[0].values.map(values => Object.fromEntries(columns.map((column, index) => [column, values[index]]))); }
function one(db, sql, params = []) { return rows(db, sql, params)[0]; }
function run(db, sql, params = []) { db.run(sql, params); }
function save(db) { fs.writeFileSync(DB_FILE, Buffer.from(db.export())); }
function safeUser(user) { if (!user) return null; const { passwordHash, ...publicUser } = user; return publicUser; }
function nextId(db, table) { return (one(db, `SELECT COALESCE(MAX(id), 0) + 1 AS id FROM ${table}`) || { id: 1 }).id; }
function userById(db, id) { return one(db, 'SELECT id, employeeId, name, email, passwordHash, role, department, jobTitle, phone, address, salary, managerId FROM users WHERE id = ?', [id]); }
function userDto(user) { return user ? { ...safeUser(user) } : null; }

async function start() {
  const SQL = await initSqlJs({ locateFile: file => path.join(__dirname, 'node_modules', 'sql.js', 'dist', file) });
  const db = fs.existsSync(DB_FILE) ? new SQL.Database(fs.readFileSync(DB_FILE)) : new SQL.Database();
  db.run(`PRAGMA foreign_keys = ON; CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, employeeId TEXT UNIQUE NOT NULL, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, passwordHash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('employee','manager','hr')), department TEXT NOT NULL, jobTitle TEXT NOT NULL, phone TEXT DEFAULT '', address TEXT DEFAULT '', salary INTEGER DEFAULT 0, managerId INTEGER); CREATE TABLE IF NOT EXISTS attendance (id INTEGER PRIMARY KEY, userId INTEGER NOT NULL, workDate TEXT NOT NULL, checkIn TEXT, checkOut TEXT, status TEXT NOT NULL DEFAULT 'Present', UNIQUE(userId, workDate)); CREATE TABLE IF NOT EXISTS leaveRequests (id INTEGER PRIMARY KEY, userId INTEGER NOT NULL, type TEXT NOT NULL, startDate TEXT NOT NULL, endDate TEXT NOT NULL, days INTEGER NOT NULL, remarks TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'Pending', managerComment TEXT DEFAULT '', createdAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS payroll (id INTEGER PRIMARY KEY, userId INTEGER UNIQUE NOT NULL, grossPay INTEGER NOT NULL, deductions INTEGER NOT NULL DEFAULT 0, netPay INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS performance (id INTEGER PRIMARY KEY, userId INTEGER UNIQUE NOT NULL, managerId INTEGER, goal TEXT NOT NULL, progress INTEGER NOT NULL, reviewStatus TEXT NOT NULL, feedback TEXT DEFAULT '', commitmentStatus TEXT NOT NULL, updatedAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS auditEvents (id INTEGER PRIMARY KEY, actorId INTEGER NOT NULL, action TEXT NOT NULL, entity TEXT NOT NULL, entityId INTEGER, details TEXT DEFAULT '', createdAt TEXT NOT NULL);`);
  if (!one(db, 'SELECT id FROM users LIMIT 1') && fs.existsSync(LEGACY_FILE)) migrateLegacy(db, JSON.parse(fs.readFileSync(LEGACY_FILE, 'utf8')));
  if (!one(db, 'SELECT id FROM users LIMIT 1')) seed(db);
  save(db);

  const app = express();
  app.use(express.json());
  app.use((req, res, next) => { res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization'); res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, OPTIONS'); if (req.method === 'OPTIONS') return res.sendStatus(204); next(); });
  app.use(express.static(__dirname));
  const tokenFor = user => jwt.sign({ id: user.id, role: user.role }, JWT_SECRET, { expiresIn: '8h' });
  const auth = (req, res, next) => { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.user = jwt.verify(token, JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Invalid or expired session' }); } };
  const managementOnly = (req, res, next) => ['hr', 'manager'].includes(req.user.role) ? next() : res.status(403).json({ error: 'Management access required' });
  const canManage = (req, employee) => req.user.role === 'hr' || (req.user.role === 'manager' && employee?.managerId === req.user.id);
  const audit = (req, action, entity, entityId, details = '') => { run(db, 'INSERT INTO auditEvents (id, actorId, action, entity, entityId, details, createdAt) VALUES (?, ?, ?, ?, ?, ?, ?)', [nextId(db, 'auditEvents'), req.user.id, action, entity, entityId, details, new Date().toISOString()]); save(db); };

  app.post('/api/auth/signup', (req, res) => { const { employeeId, name, email, password, department = 'General', jobTitle = 'Employee' } = req.body; if (!employeeId || !name || !email || !password || password.length < 8) return res.status(400).json({ error: 'Employee ID, name, email, and an 8+ character password are required' }); if (one(db, 'SELECT id FROM users WHERE email = ? OR employeeId = ?', [email.toLowerCase(), employeeId])) return res.status(409).json({ error: 'Employee ID or email is already registered' }); const id = nextId(db, 'users'); run(db, 'INSERT INTO users (id, employeeId, name, email, passwordHash, role, department, jobTitle) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', [id, employeeId, name, email.toLowerCase(), bcrypt.hashSync(password, 10), 'employee', department, jobTitle]); save(db); const user = userById(db, id); res.status(201).json({ user: userDto(user), token: tokenFor(user) }); });
  app.post('/api/auth/signin', (req, res) => { const user = one(db, 'SELECT * FROM users WHERE email = ?', [req.body.email?.toLowerCase()]); if (!user || !bcrypt.compareSync(req.body.password || '', user.passwordHash)) return res.status(401).json({ error: 'Incorrect email or password' }); res.json({ user: userDto(user), token: tokenFor(user) }); });
  app.get('/api/me', auth, (req, res) => res.json(userDto(userById(db, req.user.id))));
  app.patch('/api/me', auth, (req, res) => { const user = userById(db, req.user.id); if (!user) return res.status(404).json({ error: 'User not found' }); run(db, 'UPDATE users SET phone = ?, address = ? WHERE id = ?', [typeof req.body.phone === 'string' ? req.body.phone.trim().slice(0, 40) : user.phone, typeof req.body.address === 'string' ? req.body.address.trim().slice(0, 160) : user.address, user.id]); save(db); res.json(userDto(userById(db, user.id))); });
  app.get('/api/dashboard', auth, (req, res) => res.json({ user: userDto(userById(db, req.user.id)), attendance: rows(db, 'SELECT * FROM attendance WHERE userId = ? ORDER BY workDate DESC', [req.user.id]), leave: rows(db, 'SELECT * FROM leaveRequests WHERE userId = ? ORDER BY createdAt DESC', [req.user.id]), leaveBalance: 14 }));
  app.get('/api/notifications', auth, (req, res) => res.json(rows(db, "SELECT id, 'Leave request ' || lower(status) AS title, type || ': ' || startDate || ' - ' || endDate AS message, createdAt FROM leaveRequests WHERE userId = ? AND status != 'Pending'", [req.user.id])));
  app.post('/api/assistant', auth, (req, res) => { const question = String(req.body.question || '').toLowerCase(); if (!question.trim()) return res.status(400).json({ error: 'Ask a question about your portfolio' }); const leave = rows(db, 'SELECT * FROM leaveRequests WHERE userId = ?', [req.user.id]); const pay = one(db, 'SELECT * FROM payroll WHERE userId = ?', [req.user.id]); const attendance = rows(db, 'SELECT * FROM attendance WHERE userId = ?', [req.user.id]); const performance = one(db, 'SELECT * FROM performance WHERE userId = ?', [req.user.id]); let answer = `I can help with your attendance, leave, payroll, or performance portfolio.`; if (/leave|time off/.test(question)) answer = `You have ${leave.filter(item => item.status === 'Pending').length} pending leave requests and ${leave.filter(item => item.status === 'Approved').reduce((sum, item) => sum + item.days, 0)} approved leave days. Your current balance is 14 days.`; else if (/pay|salary|payroll/.test(question)) answer = pay ? `Your gross pay is $${pay.grossPay.toLocaleString()}, deductions are $${pay.deductions.toLocaleString()}, and net pay is $${pay.netPay.toLocaleString()}.` : 'No payroll record is available yet.'; else if (/attendance|hours|check/.test(question)) answer = `You have ${attendance.length} attendance records, including ${attendance.filter(item => item.checkIn && item.checkOut).length} completed workdays.`; else if (/performance|goal|progress|commitment/.test(question)) answer = performance ? `Your goal is “${performance.goal}” at ${performance.progress}% progress with ${performance.commitmentStatus.toLowerCase()} commitment. Feedback: ${performance.feedback}` : 'No performance review has been recorded yet.'; res.json({ answer }); });
  app.get('/api/attendance', auth, (req, res) => res.json(rows(db, 'SELECT * FROM attendance WHERE userId = ? ORDER BY workDate DESC', [req.user.id])));
  app.post('/api/attendance/check-in', auth, (req, res) => { const workDate = req.body.workDate || new Date().toISOString().slice(0, 10); if (one(db, 'SELECT id FROM attendance WHERE userId = ? AND workDate = ?', [req.user.id, workDate])) return res.status(409).json({ error: 'Attendance already exists for this date' }); const record = { id: nextId(db, 'attendance'), userId: req.user.id, workDate, checkIn: new Date().toTimeString().slice(0, 5), checkOut: null, status: 'Present' }; run(db, 'INSERT INTO attendance (id, userId, workDate, checkIn, status) VALUES (?, ?, ?, ?, ?)', [record.id, record.userId, record.workDate, record.checkIn, record.status]); save(db); res.status(201).json(record); });
  app.patch('/api/attendance/check-out', auth, (req, res) => { const workDate = req.body.workDate || new Date().toISOString().slice(0, 10); const record = one(db, 'SELECT * FROM attendance WHERE userId = ? AND workDate = ?', [req.user.id, workDate]); if (!record) return res.status(404).json({ error: 'Check-in record not found for this date' }); run(db, 'UPDATE attendance SET checkOut = ? WHERE id = ?', [new Date().toTimeString().slice(0, 5), record.id]); save(db); res.json(one(db, 'SELECT * FROM attendance WHERE id = ?', [record.id])); });
  app.get('/api/admin/attendance', auth, managementOnly, (req, res) => res.json(rows(db, 'SELECT attendance.*, users.name AS employeeName FROM attendance JOIN users ON users.id = attendance.userId ORDER BY workDate DESC')));
  app.get('/api/leaves', auth, (req, res) => res.json(rows(db, 'SELECT * FROM leaveRequests WHERE userId = ? ORDER BY createdAt DESC', [req.user.id])));
  app.post('/api/leaves', auth, (req, res) => { const { type, startDate, endDate, days, remarks = '' } = req.body; if (!type || !startDate || !endDate || !days || new Date(endDate) < new Date(startDate) || Number(days) < 1) return res.status(400).json({ error: 'Leave type, valid dates, and duration are required' }); const leave = { id: nextId(db, 'leaveRequests'), userId: req.user.id, type, startDate, endDate, days: Number(days), remarks: String(remarks).slice(0, 500), status: 'Pending', managerComment: '', createdAt: new Date().toISOString() }; run(db, 'INSERT INTO leaveRequests (id,userId,type,startDate,endDate,days,remarks,status,managerComment,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?)', Object.values(leave)); save(db); res.status(201).json(leave); });
  app.get('/api/payroll', auth, (req, res) => { const payroll = one(db, 'SELECT * FROM payroll WHERE userId = ?', [req.user.id]); if (!payroll) return res.status(404).json({ error: 'Payroll record not found' }); res.json(payroll); });
  app.get('/api/performance', auth, (req, res) => res.json(rows(db, 'SELECT * FROM performance WHERE userId = ?', [req.user.id])));
  app.get('/api/admin/performance', auth, managementOnly, (req, res) => res.json(rows(db, 'SELECT performance.*, users.name AS employeeName FROM performance JOIN users ON users.id = performance.userId')));
  app.get('/api/admin/employees', auth, managementOnly, (req, res) => { const sql = req.user.role === 'hr' ? 'SELECT * FROM users' : 'SELECT * FROM users WHERE managerId = ?'; res.json(rows(db, sql, req.user.role === 'hr' ? [] : [req.user.id]).map(userDto)); });
  app.get('/api/admin/leaves', auth, managementOnly, (req, res) => res.json(rows(db, "SELECT leaveRequests.*, users.name AS employeeName FROM leaveRequests JOIN users ON users.id = leaveRequests.userId WHERE ? = 'hr' OR users.managerId = ?", [req.user.role, req.user.id])));
  app.patch('/api/admin/leaves/:id', auth, managementOnly, (req, res) => { const leave = one(db, 'SELECT * FROM leaveRequests WHERE id = ?', [Number(req.params.id)]); if (!leave) return res.status(404).json({ error: 'Leave request not found' }); if (!canManage(req, userById(db, leave.userId))) return res.status(403).json({ error: 'You cannot manage this employee' }); if (!['Approved', 'Rejected'].includes(req.body.status)) return res.status(400).json({ error: 'Status must be Approved or Rejected' }); run(db, 'UPDATE leaveRequests SET status = ?, managerComment = ? WHERE id = ?', [req.body.status, req.body.comment || '', leave.id]); save(db); audit(req, `leave_${req.body.status.toLowerCase()}`, 'leave', leave.id, req.body.comment || ''); res.json(one(db, 'SELECT * FROM leaveRequests WHERE id = ?', [leave.id])); });
  app.patch('/api/admin/employees/:id/payroll', auth, managementOnly, (req, res) => { const employee = userById(db, Number(req.params.id)); if (!employee) return res.status(404).json({ error: 'Employee not found' }); if (!canManage(req, employee)) return res.status(403).json({ error: 'You cannot manage this employee' }); const grossPay = Number(req.body.grossPay); const deductions = Number(req.body.deductions || 0); if (!grossPay || grossPay < deductions) return res.status(400).json({ error: 'Valid salary values are required' }); const existing = one(db, 'SELECT id FROM payroll WHERE userId = ?', [employee.id]); if (existing) run(db, 'UPDATE payroll SET grossPay = ?, deductions = ?, netPay = ? WHERE userId = ?', [grossPay, deductions, grossPay - deductions, employee.id]); else run(db, 'INSERT INTO payroll (id,userId,grossPay,deductions,netPay) VALUES (?,?,?,?,?)', [nextId(db, 'payroll'), employee.id, grossPay, deductions, grossPay - deductions]); save(db); audit(req, 'payroll_updated', 'payroll', employee.id); res.json(one(db, 'SELECT * FROM payroll WHERE userId = ?', [employee.id])); });
  app.patch('/api/admin/employees/:id/performance', auth, managementOnly, (req, res) => { const employee = userById(db, Number(req.params.id)); if (!employee) return res.status(404).json({ error: 'Employee not found' }); if (!canManage(req, employee)) return res.status(403).json({ error: 'You cannot manage this employee' }); const values = [req.body.goal || '', Math.min(100, Math.max(0, Number(req.body.progress || 0))), req.body.reviewStatus || 'On track', req.body.feedback || '', req.body.commitmentStatus || 'High', new Date().toISOString()]; const existing = one(db, 'SELECT id FROM performance WHERE userId = ?', [employee.id]); if (existing) run(db, 'UPDATE performance SET goal = ?, progress = ?, reviewStatus = ?, feedback = ?, commitmentStatus = ?, updatedAt = ?, managerId = ? WHERE userId = ?', [...values, req.user.id, employee.id]); else run(db, 'INSERT INTO performance (id,userId,managerId,goal,progress,reviewStatus,feedback,commitmentStatus,updatedAt) VALUES (?,?,?,?,?,?,?,?,?)', [nextId(db, 'performance'), employee.id, req.user.id, ...values]); save(db); audit(req, 'performance_updated', 'performance', employee.id); res.json(one(db, 'SELECT * FROM performance WHERE userId = ?', [employee.id])); });
  app.use('/api', (req, res) => res.status(404).json({ error: 'API endpoint not found' }));
  app.use((error, req, res, next) => req.path.startsWith('/api') ? res.status(400).json({ error: 'Invalid JSON request body' }) : next(error));
  app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));
  app.listen(PORT, () => console.log(`Dayflow running at http://localhost:${PORT}`));
}
function migrateLegacy(db, legacy) { const users = legacy.users || []; for (const user of users) run(db, 'INSERT OR IGNORE INTO users VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', [user.id, user.employeeId, user.name, user.email, user.passwordHash, user.role === 'hr' ? 'hr' : user.role === 'manager' ? 'manager' : 'employee', user.department, user.jobTitle, user.phone || '', user.address || '', user.salary || 0, user.managerId || null]); for (const item of legacy.attendance || []) run(db, 'INSERT OR IGNORE INTO attendance VALUES (?,?,?,?,?,?)', [item.id, item.userId, item.workDate, item.checkIn, item.checkOut, item.status]); for (const item of legacy.leaveRequests || []) run(db, 'INSERT OR IGNORE INTO leaveRequests VALUES (?,?,?,?,?,?,?,?,?,?)', [item.id, item.userId, item.type, item.startDate, item.endDate, item.days, item.remarks || '', item.status, item.managerComment || '', item.createdAt || new Date().toISOString()]); for (const item of legacy.payroll || []) run(db, 'INSERT OR IGNORE INTO payroll VALUES (?,?,?,?,?)', [item.id, item.userId, item.grossPay, item.deductions, item.netPay]); for (const item of legacy.performance || []) run(db, 'INSERT OR IGNORE INTO performance VALUES (?,?,?,?,?,?,?,?,?)', [item.id, item.userId, item.managerId, item.goal, item.progress, item.reviewStatus, item.feedback, item.commitmentStatus, item.updatedAt]); for (const item of legacy.auditEvents || []) run(db, 'INSERT OR IGNORE INTO auditEvents VALUES (?,?,?,?,?,?,?)', [item.id, item.actorId, item.action, item.entity, item.entityId, item.details || '', item.createdAt]); }
function seed(db) { const users = [{ id: 1, employeeId: 'DF-2048', name: 'Alex Smith', email: 'alex.smith@dayflow.co', passwordHash: bcrypt.hashSync('dayflow123', 10), role: 'employee', department: 'Design', jobTitle: 'Product designer', phone: '+1 555 019 2048', address: 'New York, NY', salary: 6200, managerId: 3 }, { id: 2, employeeId: 'DF-1001', name: 'Maya Chen', email: 'maya.chen@dayflow.co', passwordHash: bcrypt.hashSync('admin123', 10), role: 'hr', department: 'People Ops', jobTitle: 'HR manager', phone: '+1 555 019 1001', address: 'New York, NY', salary: 7800, managerId: null }, { id: 3, employeeId: 'DF-1002', name: 'Jordan Miller', email: 'jordan.miller@dayflow.co', passwordHash: bcrypt.hashSync('manager123', 10), role: 'manager', department: 'Design', jobTitle: 'Design manager', phone: '+1 555 019 1002', address: 'New York, NY', salary: 7200, managerId: null }]; for (const user of users) run(db, 'INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', Object.values(user)); }
start().catch(error => { console.error(error); process.exit(1); });
