const path = require('path');
const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const low = require('lowdb');
const FileSync = require('lowdb/adapters/FileSync');

const app = express();
const db = low(new FileSync(path.join(__dirname, 'dayflow-db.json')));
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'dayflow-development-secret';
app.use(express.json());
app.use(express.static(__dirname));

db.defaults({ users: [], attendance: [], leaveRequests: [], payroll: [], performance: [], auditEvents: [] }).write();
function nextId(collection) { return collection.reduce((max, item) => Math.max(max, item.id), 0) + 1; }
function safeUser(user) { const { passwordHash, ...publicUser } = user; return publicUser; }
function seed() {
  const users = [{ id: 1, employeeId: 'DF-2048', name: 'Alex Smith', email: 'alex.smith@dayflow.co', passwordHash: bcrypt.hashSync('dayflow123', 10), role: 'employee', department: 'Design', jobTitle: 'Product designer', phone: '+1 555 019 2048', address: 'New York, NY', salary: 6200, managerId: 3 }, { id: 2, employeeId: 'DF-1001', name: 'Maya Chen', email: 'maya.chen@dayflow.co', passwordHash: bcrypt.hashSync('admin123', 10), role: 'hr', department: 'People Ops', jobTitle: 'HR manager', phone: '+1 555 019 1001', address: 'New York, NY', salary: 7800 }, { id: 3, employeeId: 'DF-1002', name: 'Jordan Miller', email: 'jordan.miller@dayflow.co', passwordHash: bcrypt.hashSync('manager123', 10), role: 'manager', department: 'Design', jobTitle: 'Design manager', phone: '+1 555 019 1002', address: 'New York, NY', salary: 7200 }];
  db.set('users', users).set('attendance', [{ id: 1, userId: 1, workDate: '2024-10-21', checkIn: '08:54', checkOut: '16:12', status: 'Present' }, { id: 2, userId: 1, workDate: '2024-10-18', checkIn: '09:02', checkOut: '17:21', status: 'Present' }, { id: 3, userId: 1, workDate: '2024-10-17', checkIn: '08:47', checkOut: '13:05', status: 'Half-day' }, { id: 4, userId: 2, workDate: '2024-10-21', checkIn: '08:31', checkOut: null, status: 'Present' }, { id: 5, userId: 3, workDate: '2024-10-21', checkIn: '08:18', checkOut: null, status: 'Present' }]).set('leaveRequests', [{ id: 1, userId: 1, type: 'Paid leave', startDate: '2024-11-04', endDate: '2024-11-05', days: 2, remarks: 'Personal time', status: 'Pending', managerComment: '', createdAt: new Date().toISOString() }, { id: 2, userId: 1, type: 'Sick leave', startDate: '2024-09-02', endDate: '2024-09-02', days: 1, remarks: 'Not feeling well', status: 'Approved', managerComment: '', createdAt: new Date().toISOString() }]).set('payroll', [{ id: 1, userId: 1, grossPay: 6200, deductions: 1380, netPay: 4820 }, { id: 2, userId: 2, grossPay: 7800, deductions: 1716, netPay: 6084 }, { id: 3, userId: 3, grossPay: 7200, deductions: 1584, netPay: 5616 }]).set('performance', [{ id: 1, userId: 1, managerId: 3, goal: 'Ship the new design system', progress: 72, reviewStatus: 'On track', feedback: 'Strong collaboration across product and engineering.', commitmentStatus: 'High', updatedAt: new Date().toISOString() }]).write();
}
seed();
function tokenFor(user) { return jwt.sign({ id: user.id, role: user.role }, JWT_SECRET, { expiresIn: '8h' }); }
function auth(req, res, next) { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.user = jwt.verify(token, JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Invalid or expired session' }); } }
function hrOnly(req, res, next) { if (req.user.role !== 'hr') return res.status(403).json({ error: 'HR access required' }); next(); }
function managementOnly(req, res, next) { if (!['hr', 'manager'].includes(req.user.role)) return res.status(403).json({ error: 'Management access required' }); next(); }
function userById(id) { return db.get('users').find({ id }).value(); }
function canManage(req, employee) { return req.user.role === 'hr' || (req.user.role === 'manager' && employee && employee.managerId === req.user.id); }
function audit(req, action, entity, entityId, details = '') { db.get('auditEvents').push({ id: nextId(db.get('auditEvents').value()), actorId: req.user.id, action, entity, entityId, details, createdAt: new Date().toISOString() }).write(); }
app.post('/api/auth/signup', (req, res) => { const { employeeId, name, email, password, department = 'General', jobTitle = 'Employee' } = req.body; if (!employeeId || !name || !email || !password || password.length < 8) return res.status(400).json({ error: 'Employee ID, name, email, and an 8+ character password are required' }); if (db.get('users').find(user => user.email === email.toLowerCase() || user.employeeId === employeeId).value()) return res.status(409).json({ error: 'Employee ID or email is already registered' }); const user = { id: nextId(db.get('users').value()), employeeId, name, email: email.toLowerCase(), passwordHash: bcrypt.hashSync(password, 10), role: 'employee', department, jobTitle, phone: '', address: '', salary: 0, managerId: null }; db.get('users').push(user).write(); res.status(201).json({ user: safeUser(user), token: tokenFor(user) }); });
app.post('/api/auth/signin', (req, res) => { const user = db.get('users').find(item => item.email === req.body.email?.toLowerCase()).value(); if (!user || !bcrypt.compareSync(req.body.password || '', user.passwordHash)) return res.status(401).json({ error: 'Incorrect email or password' }); res.json({ user: safeUser(user), token: tokenFor(user) }); });
app.get('/api/me', auth, (req, res) => res.json(safeUser(userById(req.user.id))));
app.get('/api/dashboard', auth, (req, res) => res.json({ user: safeUser(userById(req.user.id)), attendance: db.get('attendance').filter({ userId: req.user.id }).value(), leave: db.get('leaveRequests').filter({ userId: req.user.id }).value(), leaveBalance: 14 }));
app.get('/api/attendance', auth, (req, res) => res.json(db.get('attendance').filter({ userId: req.user.id }).value()));
app.get('/api/leaves', auth, (req, res) => res.json(db.get('leaveRequests').filter({ userId: req.user.id }).value()));
app.post('/api/leaves', auth, (req, res) => { const { type, startDate, endDate, days, remarks = '' } = req.body; if (!type || !startDate || !endDate || !days) return res.status(400).json({ error: 'Leave type, dates, and duration are required' }); const leave = { id: nextId(db.get('leaveRequests').value()), userId: req.user.id, type, startDate, endDate, days: Number(days), remarks, status: 'Pending', managerComment: '', createdAt: new Date().toISOString() }; db.get('leaveRequests').push(leave).write(); res.status(201).json(leave); });
app.get('/api/payroll', auth, (req, res) => res.json(db.get('payroll').find({ userId: req.user.id }).value()));
app.get('/api/performance', auth, (req, res) => res.json(db.get('performance').filter({ userId: req.user.id }).value()));
app.get('/api/admin/performance', auth, managementOnly, (req, res) => res.json(db.get('performance').filter(item => canManage(req, userById(item.userId))).map(item => ({ ...item, employeeName: userById(item.userId)?.name || 'Unknown employee' })).value()));
app.get('/api/admin/employees', auth, managementOnly, (req, res) => res.json(db.get('users').filter(user => req.user.role === 'hr' || user.managerId === req.user.id).map(user => safeUser(user)).value()));
app.get('/api/admin/leaves', auth, managementOnly, (req, res) => res.json(db.get('leaveRequests').filter(leave => canManage(req, userById(leave.userId))).map(leave => ({ ...leave, employeeName: userById(leave.userId)?.name || 'Unknown employee' })).value()));
app.patch('/api/admin/leaves/:id', auth, managementOnly, (req, res) => { if (!['Approved', 'Rejected'].includes(req.body.status)) return res.status(400).json({ error: 'Status must be Approved or Rejected' }); const leave = db.get('leaveRequests').find({ id: Number(req.params.id) }).value(); if (!leave) return res.status(404).json({ error: 'Leave request not found' }); if (!canManage(req, userById(leave.userId))) return res.status(403).json({ error: 'You cannot manage this employee' }); const updated = db.get('leaveRequests').find({ id: leave.id }).assign({ status: req.body.status, managerComment: req.body.comment || '' }).write(); audit(req, `leave_${req.body.status.toLowerCase()}`, 'leave', leave.id, req.body.comment || ''); res.json(updated); });
app.patch('/api/admin/employees/:id/payroll', auth, hrOnly, (req, res) => { const employee = userById(Number(req.params.id)); if (!employee) return res.status(404).json({ error: 'Employee not found' }); const grossPay = Number(req.body.grossPay); const deductions = Number(req.body.deductions || 0); if (!grossPay || grossPay < deductions) return res.status(400).json({ error: 'Valid salary values are required' }); const existing = db.get('payroll').find({ userId: employee.id }); const payroll = existing.value() ? existing.assign({ grossPay, deductions, netPay: grossPay - deductions }).write() : db.get('payroll').push({ id: nextId(db.get('payroll').value()), userId: employee.id, grossPay, deductions, netPay: grossPay - deductions }).write().find(item => item.userId === employee.id); audit(req, 'payroll_updated', 'payroll', employee.id); res.json(payroll); });
app.patch('/api/admin/employees/:id/performance', auth, managementOnly, (req, res) => { const employee = userById(Number(req.params.id)); if (!employee) return res.status(404).json({ error: 'Employee not found' }); if (!canManage(req, employee)) return res.status(403).json({ error: 'You cannot manage this employee' }); const update = { userId: employee.id, managerId: req.user.id, goal: req.body.goal || '', progress: Math.min(100, Math.max(0, Number(req.body.progress || 0))), reviewStatus: req.body.reviewStatus || 'On track', feedback: req.body.feedback || '', commitmentStatus: req.body.commitmentStatus || 'High', updatedAt: new Date().toISOString() }; const existing = db.get('performance').find({ userId: employee.id }); const performance = existing.value() ? existing.assign(update).write() : db.get('performance').push({ id: nextId(db.get('performance').value()), ...update }).write().find(item => item.userId === employee.id); audit(req, 'performance_updated', 'performance', employee.id); res.json(performance); });
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));
app.listen(PORT, () => console.log(`Dayflow running at http://localhost:${PORT}`));
