const path = require('path');
const fs = require('fs');
const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { MongoClient } = require('mongodb');

const PORT = process.env.PORT || 3000;
const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017';
const DB_NAME = process.env.MONGO_DB_NAME || 'dayflow_hrms';
const LEGACY_FILE = path.join(__dirname, 'dayflow-db.json');
const JWT_SECRET = process.env.JWT_SECRET || 'dayflow-development-secret';

const seedUsers = [
  { id: 1, employeeId: 'DF-2048', name: 'Alex Smith', email: 'alex.smith@dayflow.co', passwordHash: bcrypt.hashSync('dayflow123', 10), role: 'employee', department: 'Design', jobTitle: 'Product designer', phone: '+1 555 019 2048', address: 'New York, NY', salary: 6200, managerId: 3 },
  { id: 2, employeeId: 'DF-1001', name: 'Maya Chen', email: 'maya.chen@dayflow.co', passwordHash: bcrypt.hashSync('admin123', 10), role: 'hr', department: 'People Ops', jobTitle: 'HR manager', phone: '+1 555 019 1001', address: 'New York, NY', salary: 7800, managerId: null },
  { id: 3, employeeId: 'DF-1002', name: 'Jordan Miller', email: 'jordan.miller@dayflow.co', passwordHash: bcrypt.hashSync('manager123', 10), role: 'manager', department: 'Design', jobTitle: 'Design manager', phone: '+1 555 019 1002', address: 'New York, NY', salary: 7200, managerId: null },
  { id: 7, employeeId: 'DF-3001', name: 'Priya Nair', email: 'priya.nair@dayflow.co', passwordHash: bcrypt.hashSync('employee123', 10), role: 'employee', department: 'Engineering', jobTitle: 'Software engineer', phone: '', address: '', salary: 0, managerId: null },
  { id: 8, employeeId: 'DF-3002', name: 'Daniel Lee', email: 'daniel.lee@dayflow.co', passwordHash: bcrypt.hashSync('designer123', 10), role: 'employee', department: 'Marketing', jobTitle: 'Content designer', phone: '', address: '', salary: 0, managerId: null },
  { id: 9, employeeId: 'DF-3003', name: 'Sara Thomas', email: 'sara.thomas@dayflow.co', passwordHash: bcrypt.hashSync('engineer123', 10), role: 'employee', department: 'Finance', jobTitle: 'Financial analyst', phone: '', address: '', salary: 0, managerId: null }
];
const seedAttendance = [
  { id: 1, userId: 1, workDate: '2024-10-21', checkIn: '08:54', checkOut: '16:12', status: 'Present' },
  { id: 2, userId: 1, workDate: '2024-10-18', checkIn: '09:02', checkOut: '17:21', status: 'Present' },
  { id: 3, userId: 1, workDate: '2024-10-17', checkIn: '08:47', checkOut: '13:05', status: 'Half-day' },
  { id: 4, userId: 2, workDate: '2024-10-21', checkIn: '08:31', checkOut: null, status: 'Present' },
  { id: 5, userId: 3, workDate: '2024-10-21', checkIn: '08:18', checkOut: null, status: 'Present' }
];
const seedLeaves = [
  { id: 1, userId: 1, type: 'Paid leave', startDate: '2024-11-04', endDate: '2024-11-05', days: 2, remarks: 'Personal time', status: 'Pending', managerComment: '', createdAt: new Date().toISOString() },
  { id: 2, userId: 1, type: 'Sick leave', startDate: '2024-09-02', endDate: '2024-09-02', days: 1, remarks: 'Not feeling well', status: 'Approved', managerComment: '', createdAt: new Date().toISOString() }
];
const seedPayroll = [{ id: 1, userId: 1, grossPay: 6200, deductions: 1380, netPay: 4820 }, { id: 2, userId: 2, grossPay: 7800, deductions: 1716, netPay: 6084 }, { id: 3, userId: 3, grossPay: 7200, deductions: 1584, netPay: 5616 }];
const seedPerformance = [{ id: 1, userId: 1, managerId: 3, goal: 'Ship the new design system', progress: 72, reviewStatus: 'On track', feedback: 'Strong collaboration across product and engineering.', commitmentStatus: 'High', updatedAt: new Date().toISOString() }];

async function start() {
  const client = new MongoClient(MONGO_URI, { serverSelectionTimeoutMS: 3000 });
  try { await client.connect(); } catch (error) { console.error(`MongoDB connection failed at ${MONGO_URI}. Install/start MongoDB locally or set MONGO_URI. ${error.message}`); process.exit(1); }
  const db = client.db(DB_NAME);
  const users = db.collection('users'); const attendance = db.collection('attendance'); const leaveRequests = db.collection('leaveRequests'); const payroll = db.collection('payroll'); const performance = db.collection('performance'); const auditEvents = db.collection('auditEvents');
  await Promise.all([users.createIndex({ email: 1 }, { unique: true }), users.createIndex({ employeeId: 1 }, { unique: true }), attendance.createIndex({ userId: 1, workDate: 1 }, { unique: true }), payroll.createIndex({ userId: 1 }, { unique: true }), performance.createIndex({ userId: 1 }, { unique: true })]);
  if (await users.countDocuments() === 0) { let legacy = null; if (fs.existsSync(LEGACY_FILE)) { try { legacy = JSON.parse(fs.readFileSync(LEGACY_FILE, 'utf8')); } catch { legacy = null; } } await users.insertMany(legacy?.users?.length ? legacy.users : seedUsers); await attendance.insertMany(legacy?.attendance?.length ? legacy.attendance : seedAttendance); await leaveRequests.insertMany(legacy?.leaveRequests?.length ? legacy.leaveRequests : seedLeaves); await payroll.insertMany(legacy?.payroll?.length ? legacy.payroll : seedPayroll); await performance.insertMany(legacy?.performance?.length ? legacy.performance : seedPerformance); if (legacy?.auditEvents?.length) await auditEvents.insertMany(legacy.auditEvents); } else { for (const user of seedUsers) await users.updateOne({ email: user.email }, { $setOnInsert: user }, { upsert: true }); }
  const app = express(); app.use(express.json()); app.use((req, res, next) => { res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization'); res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, OPTIONS'); if (req.method === 'OPTIONS') return res.sendStatus(204); next(); }); app.use(express.static(__dirname));
  const userById = id => users.findOne({ id: Number(id) }); const safeUser = user => { if (!user) return null; const { passwordHash, _id, ...publicUser } = user; return publicUser; }; const nextId = async collection => ((await collection.find().sort({ id: -1 }).limit(1).next())?.id || 0) + 1;
  const tokenFor = user => jwt.sign({ id: user.id, role: user.role }, JWT_SECRET, { expiresIn: '8h' }); const auth = async (req, res, next) => { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.user = jwt.verify(token, JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Invalid or expired session' }); } }; const managementOnly = (req, res, next) => ['hr', 'manager'].includes(req.user.role) ? next() : res.status(403).json({ error: 'Management access required' }); const canManage = (req, employee) => req.user.role === 'hr' || (req.user.role === 'manager' && employee?.managerId === req.user.id); const audit = async (req, action, entity, entityId, details = '') => auditEvents.insertOne({ id: await nextId(auditEvents), actorId: req.user.id, action, entity, entityId, details, createdAt: new Date().toISOString() });

  app.post('/api/auth/signup', async (req, res) => { const { employeeId, name, email, password, department = 'General', jobTitle = 'Employee' } = req.body; if (!employeeId || !name || !email || !password || password.length < 8) return res.status(400).json({ error: 'Employee ID, name, email, and an 8+ character password are required' }); if (await users.findOne({ $or: [{ email: email.toLowerCase() }, { employeeId }] })) return res.status(409).json({ error: 'Employee ID or email is already registered' }); const user = { id: await nextId(users), employeeId, name, email: email.toLowerCase(), passwordHash: bcrypt.hashSync(password, 10), role: 'employee', department, jobTitle, phone: '', address: '', salary: 0, managerId: null }; await users.insertOne(user); res.status(201).json({ user: safeUser(user), token: tokenFor(user) }); });
  app.post('/api/auth/signin', async (req, res) => { const user = await users.findOne({ email: req.body.email?.toLowerCase() }); if (!user || !bcrypt.compareSync(req.body.password || '', user.passwordHash)) return res.status(401).json({ error: 'Incorrect email or password' }); res.json({ user: safeUser(user), token: tokenFor(user) }); });
  app.get('/api/me', auth, async (req, res) => res.json(safeUser(await userById(req.user.id))));
  app.patch('/api/me', auth, async (req, res) => { const user = await userById(req.user.id); if (!user) return res.status(404).json({ error: 'User not found' }); await users.updateOne({ id: user.id }, { $set: { phone: typeof req.body.phone === 'string' ? req.body.phone.trim().slice(0, 40) : user.phone, address: typeof req.body.address === 'string' ? req.body.address.trim().slice(0, 160) : user.address } }); res.json(safeUser(await userById(user.id))); });
  app.get('/api/dashboard', auth, async (req, res) => res.json({ user: safeUser(await userById(req.user.id)), attendance: await attendance.find({ userId: req.user.id }).sort({ workDate: -1 }).toArray(), leave: await leaveRequests.find({ userId: req.user.id }).sort({ createdAt: -1 }).toArray(), leaveBalance: 14 }));
  app.get('/api/notifications', auth, async (req, res) => res.json((await leaveRequests.find({ userId: req.user.id, status: { $ne: 'Pending' } }).toArray()).map(item => ({ id: `leave-${item.id}`, title: `Leave request ${item.status.toLowerCase()}`, message: `${item.type}: ${item.startDate} - ${item.endDate}`, createdAt: item.createdAt }))));
  app.post('/api/assistant', auth, async (req, res) => { const question = String(req.body.question || '').toLowerCase(); if (!question.trim()) return res.status(400).json({ error: 'Ask a question about your portfolio' }); const leave = await leaveRequests.find({ userId: req.user.id }).toArray(); const pay = await payroll.findOne({ userId: req.user.id }); const records = await attendance.find({ userId: req.user.id }).toArray(); const review = await performance.findOne({ userId: req.user.id }); let answer = 'I can help with your attendance, leave, payroll, or performance portfolio.'; if (/leave|time off/.test(question)) answer = `You have ${leave.filter(item => item.status === 'Pending').length} pending leave requests and ${leave.filter(item => item.status === 'Approved').reduce((sum, item) => sum + item.days, 0)} approved leave days. Your current balance is 14 days.`; else if (/pay|salary|payroll/.test(question)) answer = pay ? `Your gross pay is $${pay.grossPay.toLocaleString()}, deductions are $${pay.deductions.toLocaleString()}, and net pay is $${pay.netPay.toLocaleString()}.` : 'No payroll record is available yet.'; else if (/attendance|hours|check/.test(question)) answer = `You have ${records.length} attendance records, including ${records.filter(item => item.checkIn && item.checkOut).length} completed workdays.`; else if (/performance|goal|progress|commitment/.test(question)) answer = review ? `Your goal is “${review.goal}” at ${review.progress}% progress with ${review.commitmentStatus.toLowerCase()} commitment. Feedback: ${review.feedback}` : 'No performance review has been recorded yet.'; res.json({ answer }); });
  app.get('/api/attendance', auth, async (req, res) => res.json(await attendance.find({ userId: req.user.id }).sort({ workDate: -1 }).toArray()));
  app.post('/api/attendance/check-in', auth, async (req, res) => { const workDate = req.body.workDate || new Date().toISOString().slice(0, 10); if (await attendance.findOne({ userId: req.user.id, workDate })) return res.status(409).json({ error: 'Attendance already exists for this date' }); const record = { id: await nextId(attendance), userId: req.user.id, workDate, checkIn: new Date().toTimeString().slice(0, 5), checkOut: null, status: 'Present' }; await attendance.insertOne(record); res.status(201).json(record); });
  app.patch('/api/attendance/check-out', auth, async (req, res) => { const workDate = req.body.workDate || new Date().toISOString().slice(0, 10); const record = await attendance.findOne({ userId: req.user.id, workDate }); if (!record) return res.status(404).json({ error: 'Check-in record not found for this date' }); await attendance.updateOne({ id: record.id }, { $set: { checkOut: new Date().toTimeString().slice(0, 5) } }); res.json(await attendance.findOne({ id: record.id })); });
  app.get('/api/admin/attendance', auth, managementOnly, async (req, res) => { const list = await attendance.find().sort({ workDate: -1 }).toArray(); const result = []; for (const item of list) { const employee = await userById(item.userId); if (canManage(req, employee)) result.push({ ...item, employeeName: employee?.name || 'Unknown employee' }); } res.json(result); });
  app.get('/api/leaves', auth, async (req, res) => res.json(await leaveRequests.find({ userId: req.user.id }).sort({ createdAt: -1 }).toArray()));
  app.post('/api/leaves', auth, async (req, res) => { const { type, startDate, endDate, days, remarks = '' } = req.body; if (!type || !startDate || !endDate || !days || new Date(endDate) < new Date(startDate) || Number(days) < 1) return res.status(400).json({ error: 'Leave type, valid dates, and duration are required' }); const leave = { id: await nextId(leaveRequests), userId: req.user.id, type, startDate, endDate, days: Number(days), remarks: String(remarks).slice(0, 500), status: 'Pending', managerComment: '', createdAt: new Date().toISOString() }; await leaveRequests.insertOne(leave); res.status(201).json(leave); });
  app.get('/api/payroll', auth, async (req, res) => { const item = await payroll.findOne({ userId: req.user.id }); if (!item) return res.status(404).json({ error: 'Payroll record not found' }); res.json(item); }); app.get('/api/performance', auth, async (req, res) => res.json(await performance.find({ userId: req.user.id }).toArray()));
  app.get('/api/admin/performance', auth, managementOnly, async (req, res) => { const list = await performance.find().toArray(); const result = []; for (const item of list) { const employee = await userById(item.userId); if (canManage(req, employee)) result.push({ ...item, employeeName: employee?.name || 'Unknown employee' }); } res.json(result); });
  app.get('/api/admin/employees', auth, managementOnly, async (req, res) => { const list = await users.find(req.user.role === 'hr' ? {} : { managerId: req.user.id }).toArray(); res.json(list.map(safeUser)); }); app.get('/api/admin/leaves', auth, managementOnly, async (req, res) => { const list = await leaveRequests.find().toArray(); const result = []; for (const item of list) { const employee = await userById(item.userId); if (canManage(req, employee)) result.push({ ...item, employeeName: employee?.name || 'Unknown employee' }); } res.json(result); });
  app.patch('/api/admin/leaves/:id', auth, managementOnly, async (req, res) => { const leave = await leaveRequests.findOne({ id: Number(req.params.id) }); if (!leave) return res.status(404).json({ error: 'Leave request not found' }); if (!canManage(req, await userById(leave.userId))) return res.status(403).json({ error: 'You cannot manage this employee' }); if (!['Approved', 'Rejected'].includes(req.body.status)) return res.status(400).json({ error: 'Status must be Approved or Rejected' }); await leaveRequests.updateOne({ id: leave.id }, { $set: { status: req.body.status, managerComment: req.body.comment || '' } }); await audit(req, `leave_${req.body.status.toLowerCase()}`, 'leave', leave.id, req.body.comment || ''); res.json(await leaveRequests.findOne({ id: leave.id })); });
  app.patch('/api/admin/employees/:id/payroll', auth, managementOnly, async (req, res) => { const employee = await userById(req.params.id); if (!employee) return res.status(404).json({ error: 'Employee not found' }); if (!canManage(req, employee)) return res.status(403).json({ error: 'You cannot manage this employee' }); const grossPay = Number(req.body.grossPay); const deductions = Number(req.body.deductions || 0); if (!grossPay || grossPay < deductions) return res.status(400).json({ error: 'Valid salary values are required' }); await payroll.updateOne({ userId: employee.id }, { $set: { grossPay, deductions, netPay: grossPay - deductions } }, { upsert: true }); await audit(req, 'payroll_updated', 'payroll', employee.id); res.json(await payroll.findOne({ userId: employee.id })); });
  app.patch('/api/admin/employees/:id/performance', auth, managementOnly, async (req, res) => { const employee = await userById(req.params.id); if (!employee) return res.status(404).json({ error: 'Employee not found' }); if (!canManage(req, employee)) return res.status(403).json({ error: 'You cannot manage this employee' }); const update = { userId: employee.id, managerId: req.user.id, goal: req.body.goal || '', progress: Math.min(100, Math.max(0, Number(req.body.progress || 0))), reviewStatus: req.body.reviewStatus || 'On track', feedback: req.body.feedback || '', commitmentStatus: req.body.commitmentStatus || 'High', updatedAt: new Date().toISOString() }; await performance.updateOne({ userId: employee.id }, { $set: update }, { upsert: true }); await audit(req, 'performance_updated', 'performance', employee.id); res.json(await performance.findOne({ userId: employee.id })); });
  app.use('/api', (req, res) => res.status(404).json({ error: 'API endpoint not found' })); app.use((error, req, res, next) => req.path.startsWith('/api') ? res.status(400).json({ error: 'Invalid JSON request body' }) : next(error)); app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'index.html'))); app.listen(PORT, () => console.log(`Dayflow running at http://localhost:${PORT} using MongoDB ${DB_NAME}`));
}
start().catch(error => { console.error(error); process.exit(1); });
